---

- hosts: all
  become: true
  tasks:

  - name: delete  phpsupport for apache
    apt:
      name: libapache2-mod-php
      state: absent

  - name: delete apache2 package
    apt:
      name: apache2
      state: absent
